#!/bin/bash


# Top directory to start searching for repositories
my_path=$(echo ${HOME})

# Array of directory names that contain ".git/".
# (Could also enter directories manually instead of using 'find'.)
declare -a REPOS=$(
    echo "("
    find ${my_path} -maxdepth 2 -type d -iname ".git" -printf '"%p" '
    echo ")"
    )

# Display directory name along with output of 'git status'.
echo "--------------------------------------------"
for d in "${REPOS[@]}"
do
    echo "$( dirname $d )"
    git --git-dir="$d" --work-tree="$( dirname $d )" status
    echo "--------------------------------------------"
done
