#!/bin/bash

# Run 'find' to search for all directories that contain '.git', and save
# the output to some file that can be read in here, rather than manually
# listing the path to every respository.

#declare -a REPOS=( "/home/users/laurel07/dotfiles/custom-configs"
#    "/home/users/laurel07/courses/a555/a555/"
#    "/solarstorm/laurel07/Research_repo/"
#    )

#my_path=$(echo ${HOME})

declare -a REPOS=$(
    echo "("
    find ${HOME} maxdepth 2 -type d -iname ".git" -printf '"%p" '
    echo ")"
    )

#declare -a REPOS=$(
#    echo "("
#    find /solarstorm/laurel07 -type d -iname ".git" -printf '"%p" '
#    echo ")")

echo "----------------------------------"
for d in "${REPOS[@]}"
do
    echo "$( dirname $d )"
    git --git-dir="$d" --work-tree="$( dirname $d )" status
    echo "----------------------------------"
done
    #git --git-dir="$f/.git" --work-tree="$f" status
